config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  resources :comments
  resources :posts
  resources :likes
  resources :profiles
  resources :follows
  resources :pages, only: :index
  devise_for :users

  resources :users, path: '/', param: :username, only: [:show] do
    post :follow, to: 'profiles/follows#create', as: :follow
    delete :follow, to: 'profiles/follows#destroy', as: :unfollow
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "posts#index"
end

app/models/profile.rb
class Profile < ApplicationRecord
    after_save :create_avatar

    belongs_to :user

    def create_avatar
        self.update(avatar: Faker::Avatar.image)
    end
end

app/controllers/profiles/follows_controller.rb
class Profiles::FollowsController < ApplicationController
    before_action :set_profile

    def create
        if current_user.follow(@profile.id)
            @profile.reload
            respond_to do |format|
                format.html { redirect_to @profile }
                format.js
            end
        end
    end

    def destroy
        if current_user.unfollow(@profile.id)
            @profile.reload
            respond_to do |format|
                format.html { redirect_to @profile }
                format.js { render action: :create }
            end
        end
    end

    private

    def set_profile
        @profile = Profile.find_by_username(params[:profile_username])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]
  include Followable

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
    @posts = current_user.posts.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
    # binding.break
    @posts = current_user.posts.all
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:name, :username, :bio, :avatar)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_follow_btn.html.erb
<div id="follow_btn" class="mt-2">
    <% if current_user.is_following?(profile) %>
        <%= link_to user_unfollow_path(profile.username), method: :delete,
            remote: true do %>
            <button class="py-0.5 px-3 bg-blue-400 text-sm text-white font-medium rounded">Unfollow</button>
        <% end %>
    <% else %>
        <%= link_to user_follow_path(profile.username), method: :post,
            remote: true do %>
            <button class="py-0.5 px-3 bg-blue-400 text-white text-sm font-medium rounded">Follow</button>
        <% end %>
    <% end %>
</div>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <div class="xl:max-w-5xl lg:max-w-3xl md:max-w-3xl sm:max-w-none xl:flex lg:flex md:flex sm:block mx-52 mt-6 border-b-2 border-gray-200 pb-6">
    <div class="lg:ml-32 md:ml-0 xl:block lg:block md:block sm:hidden">
      <%= image_tag profile.avatar, class: 'h-32 w-32 rounded-full bg-white border border-grey mr-3 select-none cursor-pointer' %>
    </div>
    <div class="lg:ml-20 md:ml-10">
      <div class="sm:flex md:block">
        <div class="lg:ml-32 md:ml-0 xl:hidden lg:hidden md:hidden sm:block">
          <%= image_tag profile.avatar, class: 'h-28 w-28 rounded-full bg-white border border-grey mr-3 select-none cursor-pointer' %>
        </div>
        <div class="flex items-center">
          <div class="xl:flex lg:flex md:flex sm:hidden">
            <p class="text-xl text-gray-500 mr-2 xl:mt-0 lg:mt-0 md:mt-0 sm:mb-3 font-medium "><%= profile.username %></p>
            <% if current_user.profile.username == profile.username %>
              <%= link_to "Edit Profile", edit_profile_path, class: "border-2 rounded-md border-gray-300 font-semibold text-center text-base px-3 py-1 ml-4 xl:mt-0 lg:mt-0 md:mt-0 xl:block lg:block md:block sm:hidden" %>
            <% end %>
          </div>
          <svg
            class="ml-4 w-8 h-8 sm:hidden md:block"
            aria-label="Options"
            fill="#262626"
            height="24"
            viewBox="0 0 48 48"
            width="24"
          >
            <path
              clip-rule="evenodd"
              d="M46.7 20.6l-2.1-1.1c-.4-.2-.7-.5-.8-1-.5-1.6-1.1-3.2-1.9-4.7-.2-.4-.3-.8-.1-1.2l.8-2.3c.2-.5 0-1.1-.4-1.5l-2.9-2.9c-.4-.4-1-.5-1.5-.4l-2.3.8c-.4.1-.8.1-1.2-.1-1.4-.8-3-1.5-4.6-1.9-.4-.1-.8-.4-1-.8l-1.1-2.2c-.3-.5-.8-.8-1.3-.8h-4.1c-.6 0-1.1.3-1.3.8l-1.1 2.2c-.2.4-.5.7-1 .8-1.6.5-3.2 1.1-4.6 1.9-.4.2-.8.3-1.2.1l-2.3-.8c-.5-.2-1.1 0-1.5.4L5.9 8.8c-.4.4-.5 1-.4 1.5l.8 2.3c.1.4.1.8-.1 1.2-.8 1.5-1.5 3-1.9 4.7-.1.4-.4.8-.8 1l-2.1 1.1c-.5.3-.8.8-.8 1.3V26c0 .6.3 1.1.8 1.3l2.1 1.1c.4.2.7.5.8 1 .5 1.6 1.1 3.2 1.9 4.7.2.4.3.8.1 1.2l-.8 2.3c-.2.5 0 1.1.4 1.5L8.8 42c.4.4 1 .5 1.5.4l2.3-.8c.4-.1.8-.1 1.2.1 1.4.8 3 1.5 4.6 1.9.4.1.8.4 1 .8l1.1 2.2c.3.5.8.8 1.3.8h4.1c.6 0 1.1-.3 1.3-.8l1.1-2.2c.2-.4.5-.7 1-.8 1.6-.5 3.2-1.1 4.6-1.9.4-.2.8-.3 1.2-.1l2.3.8c.5.2 1.1 0 1.5-.4l2.9-2.9c.4-.4.5-1 .4-1.5l-.8-2.3c-.1-.4-.1-.8.1-1.2.8-1.5 1.5-3 1.9-4.7.1-.4.4-.8.8-1l2.1-1.1c.5-.3.8-.8.8-1.3v-4.1c.4-.5.1-1.1-.4-1.3zM24 41.5c-9.7 0-17.5-7.8-17.5-17.5S14.3 6.5 24 6.5 41.5 14.3 41.5 24 33.7 41.5 24 41.5z"
              fill-rule="evenodd"
            ></path>
          </svg>
          <% if current_user.profile.username != profile.username %>
            <%= render 'profiles/follow_btn', profile: @profile %>
          <% end %>
        </div>
        <div class="flex py-4 w-9/12 sm:w-full justify-between">
          <span class="flex font-medium mr-1"><%= @profile.user.posts.length %><p class="ml-1 text-gray-800 font-normal">posts</p></span>
          <span class="flex font-medium mr-1">
            <span id="followers_count"><%= @profile.followers_count %></span>
            <p class="ml-1 text-gray-800 font-normal">followers</p>
          </span>
          <span class="flex font-medium">
            <span id="followings_count"><%= @profile.user.followings_count %></span>
            <p class="ml-1 text-gray-800 font-normal">following</p>
          </span>
        </div>
        <div class="sm:flex mt-2 sm:mt-5">
          <div class="px-6 sm:px-2 py-3 text-center font-semibold md:text-lg sm:text-sm pl-0">
            0 <span class="font-normal md:text-lg sm:text-sm">Posts</span>
          </div>
          <div class="px-6 sm:px-2 py-3 text-center font-semibold md:text-lg sm:text-sm">
            26 <span class="font-normal md:text-lg sm:text-sm">Followers</span>
          </div>
          <div class="px-6 sm:px-2 py-3 text-center font-semibold md:text-lg sm:text-sm">
            6 <span class="font-normal md:text-lg sm:text-sm">Following</span>
          </div>
        </div>
      </div>
      <div class="xl:block lg:block md:block sm:hidden">
        <a href="#" data-reflex="click->Like#like">Reflex</a>
        <div class="text-xl font-semibold mt-2"><%= profile.name %></div>
        <div class="text-gray-600 mt-2 mb-2"><%= profile.bio %></div>
        <div class="flex">
          <% if current_user.profile.username == profile.username %>
            <p data-action="click->modal#openModal" class="w-max py-1.5">
              <%= link_to new_post_path, class: "px-3 py-1.5 rounded font-medium bg-blue-500 text-white", remote: true do %>
                <i class="fa fa-plus mr-0.5"></i> Create post
              <% end %>
            </p>
          <% end %>
          <% if current_user.profile.username == profile.username %>
            <%= link_to "Edit Profile", edit_profile_path, class: "border-2 rounded-md border-gray-300 font-semibold text-center text-base px-3 py-1 ml-4 xl:mt-0 lg:mt-0 md:mt-0 lx:hidden lg:hidden md:hidden sm:block" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="xl:hidden lg:hidden md:hidden sm:block">
      <div class="text-xl font-semibold mt-2"><%= profile.name %></div>
      <div class="text-gray-600 mt-2 mb-2"><%= profile.bio %></div>
      <div class="flex">
        <% if current_user.profile.username == profile.username %>
          <p data-action="click->modal#openModal" class="w-max py-1.5">
            <%= link_to new_post_path, class: "px-3 py-1.5 rounded font-medium bg-blue-500 text-white", remote: true do %>
              <i class="fa fa-plus mr-0.5"></i> Create post
            <% end %>
          </p>
        <% end %>
        <% if current_user.profile.username == profile.username %>
          <%= link_to "Edit Profile", edit_profile_path, class: "border-2 rounded-md border-gray-300 font-semibold text-center text-base px-3 py-1 ml-4 xl:mt-0 lg:mt-0 md:mt-0 lx:hidden lg:hidden md:hidden sm:block" %>
        <% end %>
      </div>
    </div>
  </div>
    <!--post icon and title-->

  <div class="xl:max-w-5xl lg:max-w-3xl md:max-w-3xl sm:max-w-none w-full relative mt-6 xl:mx-48 lg:mx-32 md:mx-24" id="posts">
    <div class="my-3 xl:pr-0 lg:pr-0 md:pr-0 sm:pr-16 flex justify-center" id="postIcon">
      <%= image_tag("grid.svg", class: "w-4 mr-1") %>
      <p class="text-sm text-gray-800 font-medium">POSTS</p>
    </div>
    <div class="lg:flex md:flex sm:block flex-wrap justify-center items-center mt-3">
      <% if current_user.posts.length == 0 %>
        <h3 class="w-full mb-16 text-4xl text-center xl:ml-20 lg:ml-20 md:ml-20 sm:ml-0 mt-14 text-gray-700 font-light">No posts</h3>
      <% else %>
        <% if current_user.profile.id == profile.id %>
          <% current_user.posts.each do |post| %>
            <div class="postData xl:mr-8 lg:mr-6 md:mr-4 sm:mr-1 xl:mb-6 lg:mb-6 md:mb-6 sm:mb-1 md:flex md:justify-center sm:flex sm:justify-center">
              <%= link_to post_url(post) do %>
                <div class = "postImage xl:w-80 xl:h-80 lg:w-60 lg:h-60 md:w-48 md:h-48 sm:w-80 sm:h-80 relative">
                  <%= image_tag post.images, alt: "", class: "w-full h-full object-cover" %>
                </div>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <h3 class="w-full mb-16 text-4xl text-center xl:ml-20 lg:ml-20 md:ml-20 sm:ml-0 mt-14 text-gray-700 font-light">Posts are hidden</h3>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Show this profile", @profile %> |
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Profiles</h1>

<div id="profiles">
  <% @profiles.each do |profile| %>
    <%= render profile %>
    <p>
      <%= link_to "Show this profile", profile %>
    </p>
  <% end %>
</div>

<%= link_to "New profile", new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @profile %>

<div>
  <%= link_to "Edit this profile", edit_profile_path(@profile) %> |
  <%= link_to "Back to profiles", profiles_path %>

  <%= button_to "Destroy this profile", @profile, method: :delete %>
</div>